server {
    listen 80;
    root /var/www;
    server_name _;
    index index.html;

    # Location for 'API'
    location /api {
        index _;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' '*';
        add_header 'Access-Control-Allow-Headers' '*';

        autoindex on;
        autoindex_exact_size on;
        autoindex_format json;

        alias /var/www/files/;
    }

    # Location for frontend
    location / {
        alias /var/www/;
        try_files $uri $uri/ /index.html;
    }
}
